# -*- coding: utf-8 -*-
"""covid_19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1Lw2QAG9CylQ28k2Px7B3YrTXQouAXm
"""

import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt

csv_covid_19 = pd.read_csv('./covid_19_data.csv')
csv_covid_19.head()
country1 = "Brazil"
country2 = "Latvia"

csv_covid_19.describe()

covid_19_country1 = csv_covid_19.where(csv_covid_19["Country/Region"]==country1).sort_values(by='ObservationDate')
covid_19_country1.head()

covid_19_country2 = csv_covid_19.where(csv_covid_19["Country/Region"]==country2).sort_values(by='ObservationDate')
covid_19_country2.head()

plt.figure(figsize=(20,5))
chart = sbn.lineplot(x='ObservationDate', y='Confirmed', hue='Country/Region', marker='o', data=covid_19_country1)
chart.set_xticklabels(chart.get_xminorticklabels(), rotation=45, horizontalalignment='right')

plt.figure(figsize=(20,5))
chart = sbn.lineplot(x='ObservationDate', y='Confirmed', hue='Country/Region', marker='o', data=covid_19_country2)
chart.set_xticklabels(chart.get_xminorticklabels(), rotation=45, horizontalalignment='right')

covid_19_compare = csv_covid_19[(csv_covid_19['Country/Region']==country1) | (csv_covid_19['Country/Region']==country2)]
covid_19_compare.sort_values(by='ObservationDate').head()

plt.figure(figsize=(20,5))
chart = sbn.lineplot(x='ObservationDate', y='Confirmed', hue='Country/Region', marker='o', data=covid_19_compare)
chart.set_xticklabels(chart.get_xminorticklabels(), rotation=45, horizontalalignment='right')

