# -*- coding: utf-8 -*-
"""covid_19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1Lw2QAG9CylQ28k2Px7B3YrTXQouAXm
"""

import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt

"""## **Input of Countries (*3 Countries*)**"""

csv_covid_19 = pd.read_csv('./covid_19_data.csv')
csv_covid_19.head()
country1 = input();
country2 = input();
country3 = input();

csv_covid_19.describe()

"""## **Data treatment on Dates**"""

for index, row in csv_covid_19.iterrows():
  monthDay = row['ObservationDate'][0:5]
  csv_covid_19.loc[index, 'MonthDay'] = monthDay

csv_covid_19.head()

"""## **Frame structure for each Country selected**"""

covid_19_country1 = csv_covid_19.where(csv_covid_19["Country/Region"]==country1).sort_values(by='ObservationDate')
covid_19_country1.head()

covid_19_country2 = csv_covid_19.where(csv_covid_19["Country/Region"]==country2).sort_values(by='ObservationDate')
covid_19_country2.head()

covid_19_country3 = csv_covid_19.where(csv_covid_19["Country/Region"]==country3).sort_values(by='ObservationDate')
covid_19_country3.head()

"""## **Function to plot the graphs**

Parameters:


*   Graph -> seaborn plot;
*   Title -> String which will be the graph's title
"""

def plot_graph_confirmed_cases(graph, title):
  graph.set_ylabel('Confirmed Cases');
  graph.set_xlabel('Date');
  graph.grid(1);
  graph.set_title(title);

"""## **Analyzing graph for each country**"""

plt.figure(figsize=(20,5));

plot_graph_confirmed_cases(
    sbn.lineplot(
      x='MonthDay', 
      y='Confirmed', 
      hue='Country/Region', 
      marker='o', data=covid_19_country1), 
    'Confirmed Cases in ' + country1);

plt.xticks(
    rotation=45, 
    horizontalalignment='right', 
);

plt.figure(figsize=(20,5));

plot_graph_confirmed_cases(
    sbn.lineplot(
      x='MonthDay', 
      y='Confirmed', 
      hue='Country/Region', 
      marker='o', data=covid_19_country2), 
    'Confirmed Cases in ' + country2);

plt.xticks(
    rotation=45, 
    horizontalalignment='right', 
);

plt.figure(figsize=(20,5));

plot_graph_confirmed_cases(
    sbn.lineplot(
      x='MonthDay', 
      y='Confirmed', 
      hue='Country/Region', 
      marker='o', data=covid_19_country3), 
    'Confirmed Cases in ' + country3);

plt.xticks(
    rotation=45, 
    horizontalalignment='right', 
);

"""# **Comparing Confirmed Cases on each country**"""

covid_19_compare = csv_covid_19[(csv_covid_19['Country/Region']==country1) | (csv_covid_19['Country/Region']==country2) | (csv_covid_19['Country/Region']==country3)]
covid_19_compare.sort_values(by='ObservationDate').head()

plt.figure(figsize=(20,5));

plot_graph_confirmed_cases(
    sbn.lineplot(
      x='MonthDay', 
      y='Confirmed', 
      hue='Country/Region', 
      marker='o', data=covid_19_compare), 
    'Comparision between ' + country1 + ', ' + country2 + " and " + country3);

plt.xticks(
    rotation=45, 
    horizontalalignment='right', 
);